<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Menu.aspx.cs" Inherits="Aramark1.Menu" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
        <br />
        <br />
        <asp:RadioButton ID="Margarita" runat="server" GroupName="Pizzas" Text="Margarita - £2,60" />
        <br />
        <asp:RadioButton ID="Pepperoni" runat="server" GroupName="Pizzas" Text="Pepperoni - £2,80" />
        <br />
        <asp:Button ID="AddToOrder" runat="server" OnClick="AddToOrder_Click1" Text="Add to the order" />
        <asp:Button ID="Calculate" runat="server" OnClick="Calculate_Click" Text="Calculate total" />
        <br />
        <asp:Label ID="Label2" runat="server" Font-Bold="True" ForeColor="#993333"></asp:Label>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" DataKeyNames="OrderID" OnRowDeleting="GridView1_RowDeleting" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            <Columns>
                <asp:BoundField DataField="OrderID" HeaderText="OrderID" SortExpression="OrderID" Visible="False" />
                <asp:BoundField DataField="CustomerID" HeaderText="CustomerID" ReadOnly="True" SortExpression="CustomerID" Visible="False" />
                <asp:BoundField DataField="Pizza" HeaderText="Pizza" SortExpression="Pizza" />
                <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
                <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
            </Columns>
        </asp:GridView>
        Price:
        <asp:Label ID="PriceLabel" runat="server"></asp:Label>
        <br />
        <asp:Button ID="Checkout" runat="server" OnClick="Checkout_Click" Text="Checkout" />
        <br />
    </form>
</body>
</html>
